### ISSUE TITLE
dllがない、うごかない

### ISSUE THREAD

**Issue by hiro111suzu** [yuin/iceberg#3]
v0.9.11 win 32bit 
以下のライブラリがないので、起動できない
- libgcc_s_dw2-1.dll
- libwinpthread-1.dll

mingwのをコピーしたけど、起動しない。黙って落ちる。

**Comment by yuin** [comment]
理由は不明なのですが、32bit環境でstaticリンクオプションが効かなくなっていましたので、dllを同梱したものにリリースを差し替えました。ご確認ください。

**Comment by hiro111suzu** [comment]
正常に動作しました。
迅速な対応、ありがとうございます。
